package com.just.theme.ui.screens.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.just.theme.util.colorToHex
import com.just.theme.util.parseHexColor

data class EditableScheme(
    val primary: String,
    val onPrimary: String,
    val primaryContainer: String,
    val onPrimaryContainer: String,
    val inversePrimary: String,
    val secondary: String,
    val onSecondary: String,
    val secondaryContainer: String,
    val onSecondaryContainer: String,
    val tertiary: String,
    val onTertiary: String,
    val tertiaryContainer: String,
    val onTertiaryContainer: String,
    val background: String,
    val onBackground: String,
    val surface: String,
    val onSurface: String,
    val surfaceVariant: String,
    val onSurfaceVariant: String,
    val surfaceTint: String,
    val inverseSurface: String,
    val inverseOnSurface: String,
    val error: String,
    val onError: String,
    val errorContainer: String,
    val onErrorContainer: String,
    val outline: String,
    val outlineVariant: String,
    val scrim: String,
    val surfaceBright: String,
    val surfaceDim: String,
    val surfaceContainer: String,
    val surfaceContainerHigh: String,
    val surfaceContainerHighest: String,
    val surfaceContainerLow: String,
    val surfaceContainerLowest: String,
    val primaryFixed: String,
    val primaryFixedDim: String,
    val onPrimaryFixed: String,
    val onPrimaryFixedVariant: String,
    val secondaryFixed: String,
    val secondaryFixedDim: String,
    val onSecondaryFixed: String,
    val onSecondaryFixedVariant: String,
    val tertiaryFixed: String,
    val tertiaryFixedDim: String,
    val onTertiaryFixed: String,
    val onTertiaryFixedVariant: String,
)

fun editorStateFromScheme(s: ColorScheme): EditableScheme = EditableScheme(
    primary = colorToHex(s.primary),
    onPrimary = colorToHex(s.onPrimary),
    primaryContainer = colorToHex(s.primaryContainer),
    onPrimaryContainer = colorToHex(s.onPrimaryContainer),
    inversePrimary = colorToHex(s.inversePrimary),
    secondary = colorToHex(s.secondary),
    onSecondary = colorToHex(s.onSecondary),
    secondaryContainer = colorToHex(s.secondaryContainer),
    onSecondaryContainer = colorToHex(s.onSecondaryContainer),
    tertiary = colorToHex(s.tertiary),
    onTertiary = colorToHex(s.onTertiary),
    tertiaryContainer = colorToHex(s.tertiaryContainer),
    onTertiaryContainer = colorToHex(s.onTertiaryContainer),
    background = colorToHex(s.background),
    onBackground = colorToHex(s.onBackground),
    surface = colorToHex(s.surface),
    onSurface = colorToHex(s.onSurface),
    surfaceVariant = colorToHex(s.surfaceVariant),
    onSurfaceVariant = colorToHex(s.onSurfaceVariant),
    surfaceTint = colorToHex(s.surfaceTint),
    inverseSurface = colorToHex(s.inverseSurface),
    inverseOnSurface = colorToHex(s.inverseOnSurface),
    error = colorToHex(s.error),
    onError = colorToHex(s.onError),
    errorContainer = colorToHex(s.errorContainer),
    onErrorContainer = colorToHex(s.onErrorContainer),
    outline = colorToHex(s.outline),
    outlineVariant = colorToHex(s.outlineVariant),
    scrim = colorToHex(s.scrim),
    surfaceBright = colorToHex(s.surfaceBright),
    surfaceDim = colorToHex(s.surfaceDim),
    surfaceContainer = colorToHex(s.surfaceContainer),
    surfaceContainerHigh = colorToHex(s.surfaceContainerHigh),
    surfaceContainerHighest = colorToHex(s.surfaceContainerHighest),
    surfaceContainerLow = colorToHex(s.surfaceContainerLow),
    surfaceContainerLowest = colorToHex(s.surfaceContainerLowest),
    primaryFixed = colorToHex(s.primaryFixed),
    primaryFixedDim = colorToHex(s.primaryFixedDim),
    onPrimaryFixed = colorToHex(s.onPrimaryFixed),
    onPrimaryFixedVariant = colorToHex(s.onPrimaryFixedVariant),
    secondaryFixed = colorToHex(s.secondaryFixed),
    secondaryFixedDim = colorToHex(s.secondaryFixedDim),
    onSecondaryFixed = colorToHex(s.onSecondaryFixed),
    onSecondaryFixedVariant = colorToHex(s.onSecondaryFixedVariant),
    tertiaryFixed = colorToHex(s.tertiaryFixed),
    tertiaryFixedDim = colorToHex(s.tertiaryFixedDim),
    onTertiaryFixed = colorToHex(s.onTertiaryFixed),
    onTertiaryFixedVariant = colorToHex(s.onTertiaryFixedVariant),
)

fun buildScheme(s: EditableScheme): ColorScheme = ColorScheme(
    primary = parseHexColor(s.primary) ?: Color(0xFF6200EE),
    onPrimary = parseHexColor(s.onPrimary) ?: Color(0xFFFFFFFF),
    primaryContainer = parseHexColor(s.primaryContainer) ?: parseHexColor(s.primary) ?: Color(0xFF6200EE),
    onPrimaryContainer = parseHexColor(s.onPrimaryContainer) ?: Color(0xFF1C1B1F),
    inversePrimary = parseHexColor(s.inversePrimary) ?: parseHexColor(s.primary) ?: Color(0xFF6200EE),
    secondary = parseHexColor(s.secondary) ?: Color(0xFF03DAC6),
    onSecondary = parseHexColor(s.onSecondary) ?: Color(0xFF000000),
    secondaryContainer = parseHexColor(s.secondaryContainer) ?: parseHexColor(s.secondary) ?: Color(0xFF03DAC6),
    onSecondaryContainer = parseHexColor(s.onSecondaryContainer) ?: Color(0xFF1C1B1F),
    tertiary = parseHexColor(s.tertiary) ?: Color(0xFF018786),
    onTertiary = parseHexColor(s.onTertiary) ?: Color(0xFFFFFFFF),
    tertiaryContainer = parseHexColor(s.tertiaryContainer) ?: parseHexColor(s.tertiary) ?: Color(0xFF018786),
    onTertiaryContainer = parseHexColor(s.onTertiaryContainer) ?: Color(0xFF1C1B1F),
    background = parseHexColor(s.background) ?: Color(0xFFFFFBFE),
    onBackground = parseHexColor(s.onBackground) ?: Color(0xFF1C1B1F),
    surface = parseHexColor(s.surface) ?: Color(0xFFFFFBFE),
    onSurface = parseHexColor(s.onSurface) ?: Color(0xFF1C1B1F),
    surfaceVariant = parseHexColor(s.surfaceVariant) ?: Color(0xFFE7E0EC),
    onSurfaceVariant = parseHexColor(s.onSurfaceVariant) ?: Color(0xFF49454F),
    surfaceTint = parseHexColor(s.surfaceTint) ?: parseHexColor(s.primary) ?: Color(0xFF6200EE),
    inverseSurface = parseHexColor(s.inverseSurface) ?: Color(0xFF313033),
    inverseOnSurface = parseHexColor(s.inverseOnSurface) ?: Color(0xFFF4EFF4),
    error = parseHexColor(s.error) ?: Color(0xFFB00020),
    onError = parseHexColor(s.onError) ?: Color(0xFFFFFFFF),
    errorContainer = parseHexColor(s.errorContainer) ?: Color(0xFFFCEEEE),
    onErrorContainer = parseHexColor(s.onErrorContainer) ?: Color(0xFF410E0B),
    outline = parseHexColor(s.outline) ?: Color(0xFF79747E),
    outlineVariant = parseHexColor(s.outlineVariant) ?: Color(0xFFCAC4D0),
    scrim = parseHexColor(s.scrim) ?: Color(0xFF000000),
    surfaceBright = parseHexColor(s.surfaceBright) ?: Color(0xFFFDF7FF),
    surfaceDim = parseHexColor(s.surfaceDim) ?: Color(0xFFDED8E1),
    surfaceContainer = parseHexColor(s.surfaceContainer) ?: Color(0xFFF3EDF7),
    surfaceContainerHigh = parseHexColor(s.surfaceContainerHigh) ?: Color(0xFFE9E3EC),
    surfaceContainerHighest = parseHexColor(s.surfaceContainerHighest) ?: Color(0xFFE1DAE3),
    surfaceContainerLow = parseHexColor(s.surfaceContainerLow) ?: Color(0xFFF7F2FA),
    surfaceContainerLowest = parseHexColor(s.surfaceContainerLowest) ?: Color(0xFFFEF7FF),
    primaryFixed = parseHexColor(s.primaryFixed) ?: parseHexColor(s.primary) ?: Color(0xFF6200EE),
    primaryFixedDim = parseHexColor(s.primaryFixedDim) ?: parseHexColor(s.primary) ?: Color(0xFF4F00C8),
    onPrimaryFixed = parseHexColor(s.onPrimaryFixed) ?: Color(0xFFFFFFFF),
    onPrimaryFixedVariant = parseHexColor(s.onPrimaryFixedVariant) ?: Color(0xFF1C1B1F),
    secondaryFixed = parseHexColor(s.secondaryFixed) ?: parseHexColor(s.secondary) ?: Color(0xFF03DAC6),
    secondaryFixedDim = parseHexColor(s.secondaryFixedDim) ?: parseHexColor(s.secondary) ?: Color(0xFF02B3A6),
    onSecondaryFixed = parseHexColor(s.onSecondaryFixed) ?: Color(0xFF000000),
    onSecondaryFixedVariant = parseHexColor(s.onSecondaryFixedVariant) ?: Color(0xFF1C1B1F),
    tertiaryFixed = parseHexColor(s.tertiaryFixed) ?: parseHexColor(s.tertiary) ?: Color(0xFF018786),
    tertiaryFixedDim = parseHexColor(s.tertiaryFixedDim) ?: parseHexColor(s.tertiary) ?: Color(0xFF016C6D),
    onTertiaryFixed = parseHexColor(s.onTertiaryFixed) ?: Color(0xFFFFFFFF),
    onTertiaryFixedVariant = parseHexColor(s.onTertiaryFixedVariant) ?: Color(0xFF1C1B1F),
)

fun generateKotlinCode(s: ColorScheme): String {
    fun c(color: Color) = "Color(0x${colorToHex(color).replace("#", "")})"
    return """
val myScheme = ColorScheme(
    primary = ${c(s.primary)},
    onPrimary = ${c(s.onPrimary)},
    primaryContainer = ${c(s.primaryContainer)},
    onPrimaryContainer = ${c(s.onPrimaryContainer)},
    inversePrimary = ${c(s.inversePrimary)},
    secondary = ${c(s.secondary)},
    onSecondary = ${c(s.onSecondary)},
    secondaryContainer = ${c(s.secondaryContainer)},
    onSecondaryContainer = ${c(s.onSecondaryContainer)},
    tertiary = ${c(s.tertiary)},
    onTertiary = ${c(s.onTertiary)},
    tertiaryContainer = ${c(s.tertiaryContainer)},
    onTertiaryContainer = ${c(s.onTertiaryContainer)},
    background = ${c(s.background)},
    onBackground = ${c(s.onBackground)},
    surface = ${c(s.surface)},
    onSurface = ${c(s.onSurface)},
    surfaceVariant = ${c(s.surfaceVariant)},
    onSurfaceVariant = ${c(s.onSurfaceVariant)},
    surfaceTint = ${c(s.surfaceTint)},
    inverseSurface = ${c(s.inverseSurface)},
    inverseOnSurface = ${c(s.inverseOnSurface)},
    error = ${c(s.error)},
    onError = ${c(s.onError)},
    errorContainer = ${c(s.errorContainer)},
    onErrorContainer = ${c(s.onErrorContainer)},
    outline = ${c(s.outline)},
    outlineVariant = ${c(s.outlineVariant)},
    scrim = ${c(s.scrim)},
    surfaceBright = ${c(s.surfaceBright)},
    surfaceDim = ${c(s.surfaceDim)},
    surfaceContainer = ${c(s.surfaceContainer)},
    surfaceContainerHigh = ${c(s.surfaceContainerHigh)},
    surfaceContainerHighest = ${c(s.surfaceContainerHighest)},
    surfaceContainerLow = ${c(s.surfaceContainerLow)},
    surfaceContainerLowest = ${c(s.surfaceContainerLowest)},
    primaryFixed = ${c(s.primaryFixed)},
    primaryFixedDim = ${c(s.primaryFixedDim)},
    onPrimaryFixed = ${c(s.onPrimaryFixed)},
    onPrimaryFixedVariant = ${c(s.onPrimaryFixedVariant)},
    secondaryFixed = ${c(s.secondaryFixed)},
    secondaryFixedDim = ${c(s.secondaryFixedDim)},
    onSecondaryFixed = ${c(s.onSecondaryFixed)},
    onSecondaryFixedVariant = ${c(s.onSecondaryFixedVariant)},
    tertiaryFixed = ${c(s.tertiaryFixed)},
    tertiaryFixedDim = ${c(s.tertiaryFixedDim)},
    onTertiaryFixed = ${c(s.onTertiaryFixed)},
    onTertiaryFixedVariant = ${c(s.onTertiaryFixedVariant)}
)
    """.trimIndent()
}
